# Generated by Django 3.2.25 on 2024-07-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_povar',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_povars',
            field=models.ManyToManyField(to='cook.Povar'),
        ),
    ]
